Repository seoyeonDev/Su-p, pull requests merged in 2024-07, with the labels that each got.

#220 issue219 : 이서연 : joinedgroup : 에러 수정
  Backend/src/main/resources/sqlMapper/joinedgroup/JoinedgroupManage_SQL.xml
Labels: bug

#230 #226 : 봉선호 : member : 로그인 로직 일부 수정, 마이페이지로 정보 불러오기 등
  Frontend/src/pages/member/Login.js
  Frontend/src/pages/member/mypage/Info.js
Labels: feature

#232 issue#231 : 봉선호 : member : 로그인 로직 일부 수정, 마이페이지로 정보 불러오기 등
  Backend/src/main/java/com/example/studyproject/member/MemberController.java
  Backend/src/main/java/com/example/studyproject/member/MemberDao.java
  Backend/src/main/java/com/example/studyproject/member/MemberService.java
  Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
Labels: enhancement, feature

#233 #227 : 봉선호 : member : 탈퇴 FE, BE
  Backend/src/main/java/com/example/studyproject/member/MemberController.java
  Frontend/src/pages/member/mypage/MemberOut.js
Labels: feature

#241 #240 : 김혜원 : penalty bug : penalty xml 누락된 부분 처리
  Backend/src/main/resources/sqlMapper/penaltylog/PenaltyLogManage_SQL.xml
Labels: bug

#246 issue234 : 이서연 : member : redis 시간제한 추가
  Backend/src/main/java/com/example/studyproject/email/EmailVerificationController.java
Labels: enhancement

#247 #235 : member : login FE
  Frontend/src/pages/member/Login.js
Labels: feature

#248 issue#245 : 봉선호 : member : 마이페이지 수정, 비번 변경, 탈퇴 보완
  Backend/src/main/java/com/example/studyproject/member/MemberController.java
  Backend/src/main/java/com/example/studyproject/member/MemberService.java
  Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
  Frontend/src/pages/member/mypage/ChangePwd.js
  Frontend/src/pages/member/mypage/Info.js
  Frontend/src/pages/member/mypage/MemberOut.js
Labels: feature

#268 #257 : member : login FE
  Frontend/src/pages/member/FindId.js
Labels: feature

#260 issue#258 : 봉선호 : files : 파일 테이블 및 클래스 파일 생성
  Backend/src/main/java/com/example/studyproject/files/Files.java
  Backend/src/main/java/com/example/studyproject/files/FilesDao.java
  Backend/src/main/java/com/example/studyproject/files/FilesService.java
  Backend/src/main/java/com/example/studyproject/member/MemberController.java
  Backend/src/main/resources/SQL/DDL/files.sql
  Backend/src/main/resources/sqlMapper/files/FilesManage_SQL.xml
Labels: feature

#261 issue#259 : 봉선호 : member : FE 비밀번호 정규화
  Frontend/src/pages/member/mypage/ChangePwd.js
Labels: feature

#263 issue#262 : 봉선호 : member : BE+FE 멤버 사진 수정 및 미리보기
  Backend/src/main/java/com/example/studyproject/member/Member.java
  Backend/src/main/java/com/example/studyproject/member/MemberController.java
  Frontend/src/pages/member/mypage/Info.js
Labels: feature

#264 #254 : 김혜원 : member 회원가입 10분 안내 : member 회원가입 이메일 10분 안내 및 이미지 미리보기
  Frontend/src/pages/member/Join.js
Labels: feature

#267 #256 : member : login FE & BE
  Backend/src/main/java/com/example/studyproject/member/MemberController.java
  Backend/src/main/java/com/example/studyproject/member/MemberService.java
  Frontend/src/pages/member/Login.js
Labels: enhancement

#269 issue256 : 이서연 : member : Controller 메세지 에러 해결
  Backend/src/main/java/com/example/studyproject/member/MemberController.java
Labels: bug

#276 issue275 : 봉선호 : member : FE 마이페이지 정보수정 이메일 인증시간 추가
  Frontend/src/pages/member/mypage/Info.js
Labels: feature

#272 issue271 : 봉선호 : member : 이미지 불러오기, 수정 시 파일테이블에 저장으로 수정
  Backend/src/main/java/com/example/studyproject/files/SupFilesDao.java
  Backend/src/main/java/com/example/studyproject/files/SupFilesService.java
  Backend/src/main/java/com/example/studyproject/member/MemberController.java
  Backend/src/main/resources/sqlMapper/member/MemberManage_SQL.xml
  Backend/src/main/resources/sqlMapper/supfiles/SupFilesManage_SQL.xml
  Frontend/src/pages/member/mypage/Info.js
Labels: enhancement, feature

#278 issue275 : 봉선호 : member : BE, FE 마이페이지 접속 위한 비밀번호 검증 페이지 추가
  Backend/src/main/java/com/example/studyproject/member/MemberController.java
  Frontend/src/App.js
  Frontend/src/components/Header.js
  Frontend/src/pages/member/mypage/InputPassword.js
Labels: feature

#294 #287 : 봉선호 : react : 파일 정리
  Frontend/src/App.js
  Frontend/src/pages/mypage/ChangePwd.js
  Frontend/src/pages/mypage/Info.js
  Frontend/src/pages/mypage/InputPassword.js
  Frontend/src/pages/mypage/Left.js
  Frontend/src/pages/mypage/MemberOut.js
  Frontend/src/pages/mypage/MyPage.js
  Frontend/src/pages/studylogs/CreatePost.js
  Frontend/src/routes/Home.js
Labels: feature
