Repository seoyeonDev/Su-p, pull requests merged in 2024-06, with the labels that each got.

#153 issue#146 : 봉선호 : studygroup : selectListStudyGroup 쿼리 설명 추가
  Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
Labels: bug

#154 issue#149 : 봉선호 : studygroup : 그룹 생성 쿼리 테이블명 수정
  Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
Labels: bug

#155 issue#147 : 봉선호 : studygroup : resulttype 수정
  Backend/src/main/java/com/example/studyproject/studygroup/StudyGroup.java
  Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
  Backend/src/main/resources/sqlMapper/studygroup/StudyGroupManage_SQL.xml
Labels: bug

#161 #158 : 김혜원 : 그룹 생성시 joinedgroup도 생성 : studygroup 생성시 joinedgroup 도 생성…
  Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupService.java
  Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
Labels: feature

#178 issue#151 : 봉선호 : studygroup : 조회수 업데이트 중괄호 하나 빠진 부분 고침
  Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupService.java
Labels: bug

#171 issue#170 : 봉선호 : penaltylog : dao class -> interface로 변경
  Backend/src/main/java/com/example/studyproject/penaltylog/PenaltylogDao.java
Labels: bug

#187 #186 : 김혜원 : member 구조 잡기 : react member 구조 잡기
  Frontend/src/App.js
  Frontend/src/pages/member/FindId.js
  Frontend/src/pages/member/FindPwd.js
  Frontend/src/pages/member/Login.js
  Frontend/src/pages/member/MyPage.js
Labels: feature

#191 issue#190 : 봉선호 : vo : 페널티로그, 스터디그룹 vo 수동 생성 주석처리
  Backend/src/main/java/com/example/studyproject/penaltylog/Penaltylog.java
  Backend/src/main/java/com/example/studyproject/studygroup/StudyGroup.java
Labels: bug

#193 issue#192 : 봉선호 : studygroup : 프론트단 초기세팅에 따라 그룹 리스트 호출 메서드 리턴 변경
  Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
  Frontend/src/pages/studygroup/StudyList.js
Labels: bug

#184 #180 : 김혜원 : studylogs 수정 : studylogs 제목, 내용, update 수정
  Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsController.java
  Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsDao.java
  Backend/src/main/java/com/example/studyproject/studylogs/StudyLogsService.java
  Backend/src/main/resources/sqlMapper/studylogs/StudyLogs_SQL.xml
Labels: feature

#207 issue#206 : 봉선호 : studylogs : StudyLogs_SQL.xml 에러 수정
  Backend/src/main/resources/sqlMapper/studylogs/StudyLogs_SQL.xml
Labels: bug

#209 issue#208 : 봉선호 : penaltylog : PenaltyLogManage_SQL.xml 파일명 수정
  Backend/src/main/resources/sqlMapper/penaltylog/PenaltyLogManage_SQL.xml
Labels: bug

#214 #194 : 김혜원 : member join : member id 중복 체크 및 비밀번호 일치 여부 확인
  Frontend/src/pages/member/Join.js
Labels: feature

#211 #199 : 이서연 : member/redis : redis 연결
  Backend/pom.xml
  Backend/src/main/java/com/example/studyproject/email/EmailVerificationController.java
  Backend/src/main/java/com/example/studyproject/email/RedisConfig.java
Labels: enhancement

#204 issue#202 : 봉선호 : studygroup : 그룹 생성 시 회차 데이터 생성, 생성 및 수정 메서드 보완
  Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupController.java
  Backend/src/main/java/com/example/studyproject/studygroup/StudyGroupService.java
Labels: enhancement, feature

#210 issue#205 : 봉선호 : member : 마이페이지 FE 작업
  Frontend/public/withdrawalTerms.txt
  Frontend/src/App.js
  Frontend/src/pages/member/MyPage.js
  Frontend/src/pages/member/mypage/ChangePwd.js
  Frontend/src/pages/member/mypage/Info.js
  Frontend/src/pages/member/mypage/Left.js
  Frontend/src/pages/member/mypage/MemberOut.js
  Frontend/src/pages/member/mypage/MyPage.js
  Frontend/src/styles/components/Member.css
Labels: feature

#212 #195 : 이서연 : joinedgroup/issue195 : 조건에 따른 목록보기
  Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupController.java
  Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupDao.java
  Backend/src/main/java/com/example/studyproject/joinedgroup/JoinedgroupService.java
  Backend/src/main/resources/sqlMapper/joinedgroup/JoinedgroupManage_SQL.xml
Labels: feature

#189 Update pull_request_template.md
  .github/pull_request_template.md
Labels: enhancement
